title: myBlog
author: Tyler_R
email: fake@domain.com
description: > # this means to ignore newlines until "baseurl:"
 A blog documenting my journey
# social links
twitter_username: my-twitter-handle
github_username:  my-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
